---
- name: Configuración del sistema
  hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  tasks:
    - name: Actualiza la caché de paquetes y el sistema
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      async: 300
      poll: 0
      register: update_job

    - name: Espera finalización de actualización
      async_status:
        jid: "{{ update_job.ansible_job_id }}"
      register: update_result
      until: update_result.finished
      retries: 30
      delay: 10

    - name: Instala paquetes básicos
      apt:
        name:
          - git
          - wget
          - unzip
          - file
          - apache2
          - tcsh
          - libnuma-dev
        state: present

    - name: Instala herramientas de desarrollo y SSL
      apt:
        name:
          - build-essential
          - libssl-dev
          - openssl
          - dnsutils
        state: present

    - name: Crea certificado SSL para localhost
      shell: |
        openssl req -x509 -out localhost.crt -keyout localhost.key \
            -newkey rsa:2048 -nodes -sha256 \
            -subj '/CN=localhost' -extensions EXT -config <( \
                printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
        echo 'made key'
      args:
        executable: /bin/bash

    - name: Crea directorios para certificados SSL
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/ssl/private
        - /etc/ssl/certs

    - name: Mueve el certificado y la clave a los directorios apropiados
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: yes
        mode: '0644'
      loop:
        - { src: 'localhost.key', dest: '/etc/ssl/private/localhost.key' }
        - { src: 'localhost.crt', dest: '/etc/ssl/certs/localhost.crt' }

    - name: Crea grupos
      group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
      loop:
        - { name: 'star-web', gid: 160 }
        - { name: 'tomcat', gid: 153 }

    - name: Crea grupos adicionales
      group:
        name: "{{ item.name }}"
      loop:
        - { name: 'sandbox' }
        - { name: 'sandbox2' }

    - name: Crea usuarios
      user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        uid: "{{ item.uid }}"
        group: "{{ item.group }}"
        home: "{{ item.home }}"
        shell: /bin/bash
        create_home: yes
        system: yes
      loop:
        - { name: 'tomcat', comment: 'Tomcat User', uid: 153, group: 'star-web', home: '/home/tomcat' }
        - { name: 'starexec', comment: 'Starexec User', uid: 152, group: 'star-web', home: '/home/starexec' }
        - { name: 'sandbox', comment: 'Cluster UserOne', uid: 111, group: 'sandbox', home: '/home/sandbox' }
        - { name: 'sandbox2', comment: 'Cluster UserTwo', uid: 112, group: 'sandbox2', home: '/home/sandbox2' }

    - name: Añade usuarios a grupos
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        append: yes
      loop:
        - { name: 'sandbox', groups: 'star-web' }
        - { name: 'sandbox2', groups: 'star-web' }
        - { name: 'tomcat', groups: 'star-web,sandbox,sandbox2' }
        - { name: 'starexec', groups: 'star-web' }

    - name: Configura directorios de trabajo
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: '/export', owner: 'root', group: 'root', mode: '0755' }
        - { path: '/export/starexec', owner: 'root', group: 'root', mode: '0755' }
        - { path: '/export/starexec/sandbox', owner: 'tomcat', group: 'star-web', mode: '0755' }
        - { path: '/export/starexec/sandbox2', owner: 'tomcat', group: 'star-web', mode: '0755' }
        - { path: '/local/sandbox', owner: 'sandbox', group: 'sandbox', mode: '0770' }
        - { path: '/local/sandbox2', owner: 'sandbox2', group: 'sandbox2', mode: '0770' }

    - name: Añade permisos especiales a directorios
      file:
        path: "{{ item.path }}"
        mode: 'g+s'
      loop:
        - { path: '/local/sandbox' }
        - { path: '/local/sandbox2' }

